name: "Ssionn's Pint Of Icecream"
on:
  push:
    branches: [ production, development ]
  pull_request:
    branches: [ production, development ]
permissions:
  contents: write
  pull-requests: write
jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install Composer dependencies
      run: composer require laravel/pint --dev
    - name: Create Pint config
      run: |
        echo '{
          "preset": "laravel",
          "rules": {
            "indentation_type": true,
            "array_indentation": true,
            "binary_operator_spaces": {
              "default": "single_space"
            },
            "blank_line_before_statement": {
              "statements": ["return"]
            },
            "concat_space": {
              "spacing": "one"
            },
            "class_attributes_separation": {
              "elements": {
                "method": "one"
              }
            },
            "no_unused_imports": true,
            "ordered_imports": {
              "sort_algorithm": "alpha"
            },
            "no_extra_blank_lines": {
              "tokens": [
                "extra",
                "throw",
                "use"
              ]
            },
            "no_trailing_whitespace": true,
            "single_blank_line_at_eof": true,
            "method_argument_space": {
              "on_multiline": "ensure_fully_multiline",
              "keep_multiple_spaces_after_comma": false
            },
            "function_declaration": {
              "closure_function_spacing": "one"
            },
            "braces": {
              "position_after_functions_and_oop_constructs": "next"
            },
            "phpdoc_to_comment": false,
            "no_empty_phpdoc": true,
            "no_superfluous_phpdoc_tags": true,
            "comment_to_phpdoc": true,
            "no_trailing_whitespace_in_comment": true,
            "single_line_comment_style": true,
            "no_empty_comment": true
          },
          "indent": "    "
        }' > pint.json
    - name: Run Laravel Pint
      run: vendor/bin/pint --config pint.json
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Apply Laravel Pint changes
        title: Apply Laravel Pint changes
        body: This PR applies changes made by Laravel Pint.
        branch: laravel-pint-changes
        base: ${{ github.head_ref || github.ref_name }}
